version: "3.7"

services:
  service_000_storybook:
    build:
      context: ../../service_000_storybook
      dockerfile: Dockerfile-development
    container_name: service_000_storybook
    command: sh -c "yarn && yarn storybook"
    ports:
      - "8000:6006"
    volumes:
      - ../../service_000_storybook:/usr/src/service_000_storybook
    env_file:
      - ../env/storybook/dev.env

  service_001_gatsby:
    build:
      context: ../../service_001_gatsby
      dockerfile: Dockerfile-development
    container_name: service_001_gatsby
    command: sh -c "yarn && yarn develop -H 0.0.0.0"
    ports:
      - "8001:8000"
    volumes:
      - ../../service_001_gatsby:/usr/src/service_001_gatsby
    env_file:
      - ../env/gatsby/dev.env

  service_002_strapi:
    build:
      context: ../../service_002_strapi
      dockerfile: Dockerfile-development
    container_name: service_002_strapi
    command: sh -c "yarn && yarn develop"
    ports:
      - "8002:1337"
      - "8003:8000"
    volumes:
      - ../../service_002_strapi:/usr/source/service_002_strapi
    env_file:
      - ../env/strapi/dev.env
    depends_on:
      - mysql_db

  service_003_ionic:
    build:
      context: ../../service_003_ionic
      dockerfile: Dockerfile-development
    container_name: service_003_ionic
    command: sh -c "npm install && npm start"
    ports:
      - "8004:3000"
    volumes:
      - ../../service_003_ionic:/usr/src/service_003_ionic
    env_file:
      - ../env/ionic/dev.env
