version: "3.7"

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_db:/var/lib/mysql_db

  service_001_gatsby:
    build:
      context: ./service_001_gatsby
      dockerfile: Dockerfile-production
    container_name: service_001_gatsby
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production

  service_002_strapi:
    build:
      context: ./service_002_strapi
      dockerfile: Dockerfile-production
    container_name: service_002_strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=mysql_db
      - DATABASE_PORT=3306
      - DATABASE_NAME=mysql_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      - mysql_db

  service_003_ionic:
    build:
      context: ./service_003_ionic
      dockerfile: Dockerfile-production
    container_name: service_003_ionic
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      - NODE_ENV=production

volumes:
  mysql_db:
