module.exports = {
  apps: [
    {
      name: "service-000-mysql",
      cwd: "./service-000-mysql",
      script: "start-development.js",
      watch: false,
    },
    {
      name: "service-000-storybook",
      cwd: "./service-000-storybook",
      script: "start-development.js",
      watch: false,
      env: {NODE_ENV:"development"},
    },
    {
      name: "service-001-gatsby",
      cwd: "./service-001-gatsby",
      script: "start-development.js",
      watch: false,
      env: {NODE_ENV:"development"},
    },
    {
      name: "service-002-strapi",
      cwd: "./service-002-strapi",
      script: "start-development.js",
      watch: false,
      env: {NODE_ENV:"development",
HOST:"0.0.0.0",
PORT:"1337",
DATABASE_HOST:"127.0.0.1",
DATABASE_PORT:"3308",
DATABASE_NAME:"mysql_db",
DATABASE_USERNAME:"root",
DATABASE_PASSWORD:"root",
CMS_ADMIN_USER:"da_package",
CMS_ADMIN_EMAIL:"admin@dapackage.com",
CMS_ADMIN_PASSWORD:"Root_admin_123",
JWT_SECRET:"6302e01a-6044-4239-a32f-8a4728cd622a"},
    },
    {
      name: "service-003-ionic",
      cwd: "./service-003-ionic",
      script: "start-development.js",
      watch: false,
      env: {NODE_ENV:"development"},
    },
  ],
};
