mariadbHost: "erpnext-mariadb.erpnext.svc.cluster.local"
persistence:
  worker:
    size: 10Gi
    storageClass: "nfs"
  logs:
    size: 5Gi
    storageClass: "nfs"
redis:
  extraEnv:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
# TODO:
# add prometheus
