version: "3.7"

services:
  mysql_db:
    image: mysql:5.7
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql_db

  service_001_gatsby:
    build:
      context: ./service_001_gatsby
      dockerfile: Dockerfile-production
    container_name: service_001_gatsby
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - ../env/gatsby/prod.env

  service_002_strapi:
    build:
      context: ./service_002_strapi
      dockerfile: Dockerfile-production
    container_name: service_002_strapi
    restart: unless-stopped
    ports:
      - "1337:1337"
    env_file:
      - ../env/strapi/prod.env
    depends_on:
      - mysql_db

  service_003_ionic:
    build:
      context: ./service_003_ionic
      dockerfile: Dockerfile-production
    container_name: service_003_ionic
    restart: unless-stopped
    ports:
      - "8081:80"
    env_file:
      - ../env/ionic/prod.env

volumes:
  mysql_db:
