apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.network/backend: "true"
    io.kompose.service: seeder
  name: seeder
spec:
  containers:
    - args:
        - ./docker/prod/seeder
      env:
        - name: DATABASE_URL
          value: postgres://postgres:p4ssw0rd@db/openproject
        - name: IMAP_ENABLED
          value: "false"
        - name: OPENPROJECT_CACHE__MEMCACHE__SERVER
          value: cache:11211
        - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
        - name: RAILS_CACHE_STORE
          value: memcache
        - name: USE_PUMA
          value: "true"
      image: openproject/community:11
      name: seeder
      resources: {}
      volumeMounts:
        - mountPath: /var/openproject/assets
          name: opdata
  restartPolicy: OnFailure
  volumes:
    - name: opdata
      persistentVolumeClaim:
        claimName: opdata
status: {}
