apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: worker
    spec:
      containers:
        - args:
            - ./docker/prod/worker
          env:
            - name: DATABASE_URL
              value: postgres://postgres:p4ssw0rd@db/openproject
            - name: IMAP_ENABLED
              value: "false"
            - name: OPENPROJECT_CACHE__MEMCACHE__SERVER
              value: cache:11211
            - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
            - name: RAILS_CACHE_STORE
              value: memcache
            - name: USE_PUMA
              value: "true"
          image: openproject/community:11
          name: worker
          resources: {}
          volumeMounts:
            - mountPath: /var/openproject/assets
              name: opdata
      restartPolicy: Always
      volumes:
        - name: opdata
          persistentVolumeClaim:
            claimName: opdata
status: {}
