FROM google/cloud-sdk:alpine

RUN apk update
RUN apk add openjdk7 jq curl openssl tree gettext --no-cache 
RUN gcloud components install app-engine-java kubectl beta
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
    && chmod +x get_helm.sh && ./get_helm.sh
RUN curl -L https://github.com/kubernetes/kompose/releases/download/v1.22.0/kompose-linux-amd64 -o kompose \
    && chmod +x kompose \
    && mv ./kompose /usr/local/bin/kompose
RUN cd "$(mktemp -d)" \
    && OS="$(uname | tr '[:upper:]' '[:lower:]')" \
    && ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" \
    && curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" \
    && tar zxvf krew.tar.gz \
    && KREW=./krew-"${OS}_${ARCH}" \
    && "$KREW" install krew
RUN printf "# chalk initialiser\n" >> /root/.profile

ENV JAVA_HOME=/usr/lib/jvm/java-1.7-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH
ENV PATH=/root/.krew/bin:$PATH
ENV PATH=/usr/src/service-000-gcloud/src/.chalk/bin:$PATH

WORKDIR /usr/src/service-000-gcloud

COPY . ./

RUN find . -type f -iname "*.sh" -exec chmod +x {} \;
RUN find . -type f -iname "chalk" -exec chmod +x {} \;
RUN kubectl krew update \
    && kubectl krew install cert-manager \
    && kubectl krew install ingress-nginx
