mariadbHost: "erpnext-mariadb.erpnext.svc.cluster.local"
persistence:
  worker:
    storageClass: "nfs"
  logs:
    size: 1Gi
    storageClass: "nfs"
redis:
  extraEnv:
    - name: ALLOW_EMPTY_PASSWORD
      value: "yes"
