ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
  hosts:
    - gitea.hiramlabs.com
  tls:
    - hosts:
        - gitea.hiramlabs.com
      secretName: gitea-tls-secret
# service:
#   ssh:
#     annotations:
#       metallb.universe.tf/allow-shared-ip: test
