ARG node_env

FROM nikolaik/python-nodejs:python3.9-nodejs12-alpine

RUN apk update
RUN apk add build-base --no-cache 
RUN printf "# chalk initialiser\n" >> /root/.profile

ENV PYTHONUNBUFFERED=1

ENV NODE_ENV=$node_env
ENV PATH=/usr/src/service-000-selenium/src/.chalk/bin:$PATH

WORKDIR /usr/src/service-000-selenium

COPY . ./

RUN find . -type f -iname "*.sh" -exec chmod +x {} \;
RUN find . -type f -iname "chalk" -exec chmod +x {} \;
RUN cd src/python \
    && pipenv lock --pre \
    && pipenv install --dev 