ARG node_env

FROM nikolaik/python-nodejs:python3.9-nodejs12-alpine

RUN apk update
RUN apk add bash git build-base jq curl openssl tree gettext --no-cache 
RUN printf "# chalk resources\n" >> /root/.chalkrc
RUN printf "PATH=/usr/src/selenium/src/.chalk/bin:$PATH\nchalk" >> /root/.profile

ENV PYTHONUNBUFFERED=1
ENV PATH=/usr/src/selenium/src/.chalk/bin:$PATH

WORKDIR /usr/src/selenium

COPY . ./

RUN find . -type f -iname "*.sh" -exec chmod +x {} \;
RUN find . -type f -iname "chalk" -exec chmod +x {} \;
RUN cd src/python \
    && pipenv lock --pre \
    && pipenv install --dev 
