ARG node_env

FROM nikolaik/python-nodejs:python3.9-nodejs12-alpine

RUN apk update
RUN printf "# chalk initialiser\n" >> /root/.profile

ENV PYTHONUNBUFFERED=1

ENV NODE_ENV=$node_env
ENV PATH=/usr/src/service-000-selenium/src/bin:$PATH

WORKDIR /usr/src/service-000-selenium

COPY . ./

RUN cd src/python \
    && pipenv lock --pre \
    && pipenv install --dev