version: "3.7"

services:
  mysql_db:
    build:
      context: ../../service-000-mysql
      dockerfile: Dockerfile-development
    container_name: mysql_db
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - data:/var/lib/mysql
      - ../../service-000-mysql:/usr/src/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3309:8080
    depends_on:
      - mysql_db

volumes:
  data:
# adminer credentials
# server: mysql_db
# username: root
# password: p4ssw0rd
