ARG node_env

FROM mhart/alpine-node:12

RUN apk update
RUN apk add bash git alpine-sdk python2 jq tree --no-cache 
RUN printf "# chalk resources\n" >> /root/.chalkrc
RUN printf "PATH=/usr/src/storybook/src/.chalk/bin:$PATH\nchalk" >> /root/.profile

ENV PATH=/usr/src/storybook/src/.chalk/bin:$PATH

WORKDIR /usr/src/storybook

COPY . ./

RUN find . -type f -iname "*.sh" -exec chmod +x {} \;
RUN find . -type f -iname "chalk" -exec chmod +x {} \;
RUN npm install --global --save-dev --unsafe-perm=true --allow-root \
    node-sass \
    typescript \
    tslib \
    react \
    @types/react \
    react-dom \
    @types/react-dom \
    rollup \
    rollup-plugin-typescript2 \
    rollup-plugin-banner \
    rollup-plugin-scss \
    @rollup/plugin-node-resolve