ARG node_env

FROM mhart/alpine-node:12

RUN apk update
RUN apk add bash git build-base jq curl openssl tree gettext --no-cache 
RUN printf "# chalk resources\n" >> /root/.chalkrc
RUN printf "PATH=/usr/src/storybook/src/.chalk/bin:$PATH\nchalk" >> /root/.profile

ENV PATH=/usr/src/storybook/src/.chalk/bin:$PATH

WORKDIR /usr/src/storybook

COPY . ./

RUN find . -type f -iname "*.sh" -exec chmod +x {} \;
RUN find . -type f -iname "chalk" -exec chmod +x {} \;
