apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -c
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - args:
            - ./docker/prod/proxy
          env:
            - name: APP_HOST
              value: web:3000
            - name: OPENPROJECT_RAILS__RELATIVE__URL__ROOT
          image: openproject/community:11
          name: proxy
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
