ARG node_env

FROM mysql:8.0

RUN apt-get update \ 
    && apt-get install -y curl git tree vim \
    && apt-get clean 
RUN printf "# chalk resources\n" >> /root/.chalkrc
RUN printf "PATH=/usr/src/mysql/src/.chalk/bin:$PATH\nchalk" >> /root/.profile

ENV MYSQL_ROOT_USERNAME=root
ENV MYSQL_ROOT_PASSWORD=p4ssw0rd
ENV CREDENTIALS_FILE=/root/.credentials.cnf
ENV PATH=/usr/src/mysql/src/.chalk/bin:$PATH

RUN echo "[client]" > $CREDENTIALS_FILE \
    && echo "user=$MYSQL_ROOT_USERNAME" >> $CREDENTIALS_FILE \
    && echo "password=$MYSQL_ROOT_PASSWORD" >> $CREDENTIALS_FILE \
    && echo "host=127.0.0.1" >> $CREDENTIALS_FILE 

WORKDIR /usr/src/mysql

COPY . ./

RUN find . -type f -iname "*.sh" -exec chmod +x {} \;
RUN find . -type f -iname "chalk" -exec chmod +x {} \;
