grafana:
  adminPassword: prom-operator
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    hosts:
      - grafana.hiramlabs.com
    tls:
      - secretName: grafana-general-tls
        hosts:
          - grafana.hiramlabs.com
