FROM google/cloud-sdk:alpine

# Add packages to 'world' and install
RUN apk --update add openjdk7-jre

# Installing additional components
RUN gcloud components install app-engine-java kubectl beta

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/service_000_gcloud

# Copying source files
COPY . ./