FROM google/cloud-sdk:alpine

# Add packages to 'world' and install
RUN apk --update add openjdk7 jq curl openssl tree --no-cache 
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 \
    && chmod +x get_helm.sh && ./get_helm.sh
RUN curl -L https://github.com/kubernetes/kompose/releases/download/v1.22.0/kompose-linux-amd64 -o kompose \
    && chmod +x kompose \
    && mv ./kompose /usr/local/bin/kompose

# Installing additional components
RUN gcloud components install app-engine-java kubectl beta

# Add Java compiler
ENV JAVA_HOME=/usr/lib/jvm/java-1.7-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/service_000_gcloud

# Copying source files
COPY . ./